dikeomaelpidas/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("landing_page.urls")),
    path("client_messages/", include("client_messages.urls")),
    path("webtools/", include("webtools.urls")),

    path("ckeditor5/", include("django_ckeditor_5.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

landing_page/urls.py
# Django
from django.urls import path
# Local
from . import views

app_name = "landing_page"

urlpatterns = [
    path("<str:lang>/", views.index, name="index"),
    path("<str:lang>/about/", views.about, name="about"),
    path("<str:lang>/services/", views.services, name="services"),
    path("<str:lang>/events/<int:page>/", views.posts_list, name="events"),
    path("<str:lang>/event/<int:post_id>/", views.posts_detail, name="event_detail"),
    path("<str:lang>/news/<int:page>/", views.posts_list, name="news"),
    path("<str:lang>/new/<int:post_id>/", views.posts_detail, name="new_detail"),
    path("<str:lang>/contact/", views.contact, name="contact"),
    path("<str:lang>/support/", views.support, name="support"),
    path("<str:lang>/team/", views.team, name="team"),
]

webtools/urls.py
# django
from django.urls import path
# local
from . import views

app_name = "webtools"

urlpatterns = [
    path("api/get-latest-active-announcement", views.get_latest_active_announcement,
         name="api-get-latest-active-announcement"),
]

landing_page/views.py
# django
from django.contrib.admin.models import LogEntry
from django.core.paginator import Paginator
from django.shortcuts import render, redirect
from django.urls import reverse
# local
from landing_page.functions import get_team_members_data, get_posts_data, get_single_post_data, \
    get_available_programs_data
from news_and_events.models import Post
from programs.models import Program
from team_members.models import Member
from translations.decorators import get_translations_information
from webtools.decorators import get_contact_information


@get_contact_information
@get_translations_information
def index(request, lang="en"):
    """
    This view is used to render the index.html
    :param lang:
    :param request:
    :return:
    """
    template = "landing_page/index.html"
    available_programs = get_available_programs_data()
    context = {"contact_information": request.contact_information,
               "available_programs": available_programs}
    return render(request, template, context)


@get_contact_information
@get_translations_information
def about(request, lang="en"):
    """
    This view is used to render the about page
    :param lang:
    :param request:
    :return:
    """
    template = "landing_page/about.html"
    context = {"contact_information": request.contact_information}
    return render(request, template, context)


@get_contact_information
@get_translations_information
def services(request, lang="en"):
    """
    This view is used to render the services page
    :param lang:
    :param request:
    :return:
    """
    template = "landing_page/services.html"
    available_programs = get_available_programs_data()
    context = {"contact_information": request.contact_information,
               "available_programs": available_programs}
    return render(request, template, context)


@get_contact_information
@get_translations_information
def posts_list(request, lang="en", page=1):
    """
    This view is used to render the events page
    :param page:
    :param lang:
    :param request:
    :return:
    """
    template = "landing_page/posts_list.html"
    # Get full URL from request, to determine content logic
    full_url = request.get_full_path()
    if "events" in full_url:
        posts_category = "events_category"
    elif "news" in full_url:
        posts_category = "news_category"
    else:
        # In case of wrong url usage, send user to homepage
        return redirect(reverse("landing_page:index", kwargs={"lang": lang}))

    # Get all posts data
    posts_data = get_posts_data(lang, posts_category)
    # Paginate based on requested page
    posts_paginator = Paginator(posts_data, 12)
    posts_current_page = posts_paginator.get_page(page)
    context = {"contact_information": request.contact_information,
               "posts_data": posts_current_page}
    return render(request, template, context)


@get_contact_information
@get_translations_information
def posts_detail(request, lang="en", post_id=None):
    """
    View used to handle single post view
    :param request:
    :param lang:
    :param post_id:
    :return:
    """
    template = "landing_page/post_detail.html"
    # Get full URL from request, to determine content logic
    full_url = request.get_full_path()
    if "event" in full_url:
        # Redirect to homepage if post detail is accessed without id
        if not post_id:
            return redirect(reverse("landing_page:events", kwargs={"lang": lang, "page": 1}))
        posts_category = "events_category"
    elif "new" in full_url:
        # Redirect to homepage if post detail is accessed without id
        if not post_id:
            return redirect(reverse("landing_page:news", kwargs={"lang": lang, "page": 1}))
        posts_category = "news_category"
    else:
        return redirect(reverse("landing_page:index", kwargs={"lang": lang}))
    post_data = get_single_post_data(lang, post_id)
    # If no post data found redirect to the correct post page
    if not post_data:
        if "event" in full_url:
            return redirect(reverse("landing_page:events", kwargs={"lang": lang, "page": 1}))
        elif "new" in full_url:
            return redirect(reverse("landing_page:news", kwargs={"lang": lang, "page": 1}))

    # Get more articles data
    posts_data = get_posts_data(lang, posts_category)
    # Paginate based on requested page
    posts_paginator = Paginator(posts_data, 12)
    extra_posts = posts_paginator.get_page(1)
    context = {"contact_information": request.contact_information,
               "post_data": post_data,
               "extra_posts": extra_posts}
    return render(request, template, context)


@get_contact_information
@get_translations_information
def contact(request, lang="en"):
    """
    This view is used to render the contact page
    :param lang:
    :param request:
    :return:
    """
    template = "landing_page/contact.html"
    context = {"contact_information": request.contact_information}
    return render(request, template, context)


@get_contact_information
@get_translations_information
def support(request, lang="en"):
    """
    This view is used to render the support page
    :param lang:
    :param request:
    :return:
    """
    template = "landing_page/support.html"
    context = {"contact_information": request.contact_information}
    return render(request, template, context)


@get_contact_information
@get_translations_information
def team(request, lang="en"):
    """
    This view is used to render the support page
    :param lang:
    :param request:
    :return:
    """
    template = "landing_page/team.html"
    team_members_data = get_team_members_data()
    context = {"contact_information": request.contact_information,
               "team_members_data": team_members_data}
    return render(request, template, context)


def dashboard_callback(request, context):
    # Gather Total Posts
    posts_count = Post.objects.count()
    context["posts_count"] = posts_count
    # Gather Total Team Members
    team_members_count = Member.objects.count()
    context["team_members_count"] = team_members_count
    # Gather Total Programs
    programs_count = Program.objects.count()
    context["programs_count"] = programs_count
    # Gather Recent Actions
    recent_actions = LogEntry.objects.all().order_by('-action_time')[:5]
    context["recent_actions"] = recent_actions
    return context

templates/landing_page/includes/footer.html
<footer>
  {% load static %}
  {% load translations_tags %}

  <div class="container">
    <div class="row">
      <div class="col-12 col-lg-5">
        <a class="navbar-brand" href="#">
          <img src="{% static 'assets/images/logo.webp' %}" alt="Dikaioma Elpidas Logo">
        </a>
        <span class="d-block footer-text mt-6">{% trans 'footer_name' %}</span>
        <a href="https://www.google.com/maps/dir/34.9208576,33.6068608/34.93273,33.63369/@34.9266741,33.5981407,14z/data=!3m1!4b1!4m4!4m3!1m1!4e1!1m0?entry=ttu&g_ep=EgoyMDI1MDMxOS4yIKXMDSoASAFQAw%3D%3D" class="d-block footer-text">Omonoias 9, Larnaca, 6058, Cyprus</a>

        <span class="d-block footer-text fs-5 mt-6">{% trans 'footer_social_Title' %}</span>

        <div class="contact-social-icons d-flex mt-3">
          <a href="https://www.facebook.com/dikaiomaelpidas" target="_blank" class="social-icon me-3 mb-lg-4">
            <i class="fa-brands fa-facebook-f"></i>
          </a>
          <a href="https://www.instagram.com/dikaioma_elpidas/" target="_blank" class="social-icon">
            <i class="fa-brands fa-instagram"></i>
          </a>
        </div>

      </div>
      <div class="d-none d-lg-block col-3">
        <span class="d-block text-white fs-5">{% trans 'footer_explore' %}</span>
        <a href="#" class="d-block text-white mt-4">{% trans 'menu_about_us' %}</a>
        <a href="#" class="d-block text-white mt-2">{% trans 'menu_support_us' %}</a>
        <a href="#" class="d-block text-white mt-2">{% trans 'menu_contact_us' %}</a>
        <a href="#" class="d-block text-white mt-2">{% trans 'menu_events' %}</a>
        <a href="#" class="d-block text-white mt-2">{% trans 'menu_actions' %}</a>
        <a href="#" class="d-block text-white mt-2">{% trans 'menu_news' %}</a>
      </div>
      <div class="d-none d-lg-block col-4 social-media-icons">
        <span class="d-block text-white fs-5">{% trans 'slug_140' %}</span>
        <a href="tel:+357 24653526" class="d-block text-white mt-4">+357 24653526</a>
        <a href="mailto:dikaiomaelpidas@gmail.com" class="d-block text-white mt-2">dikaiomaelpidas@gmail.com</a>
      </div>
    </div>
  </div>
</footer>

templates/landing_page/includes/involved-modal.html
{% load static %}
{% load translations_tags %}

<!-- Modal -->
<div class="modal fade p-0" id="involvedModal" tabindex="-1" aria-labelledby="modalTitle" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header border-0">
                <h5 class="modal-title" id="modalTitle">Modal title</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="d-flex modal-details flex-column">
                <div class="modal-body" id="first-paragraph"></div>
                <div class="modal-body" id="sec-paragraph"></div>
                <div class="modal-body" id="third-paragraph"></div>
            </div>
        </div>
    </div>
</div>

<script>
    // Select the modal element
    const modal = document.getElementById('involvedModal');

    // Event listener for when the modal is about to be shown
    modal.addEventListener('show.bs.modal', function (event) {
        // Button that triggered the modal
        const button = event.relatedTarget;

        // Extract info from data attributes
        const title = button.getAttribute('data-title');
        const first_paragraph = button.getAttribute('data-first-paragraph');
        const second_paragraph = button.getAttribute('data-sec-paragraph');
        const third_paragraph = button.getAttribute('data-third-paragraph');

        // Update the modal content
        document.getElementById('modalTitle').textContent = title;
        document.getElementById('first-paragraph').textContent = first_paragraph;
        document.getElementById('sec-paragraph').textContent = second_paragraph;
        document.getElementById('third-paragraph').textContent = third_paragraph;
    });
</script>

templates/landing_page/includes/modal.html
{% load static %}
{% load translations_tags %}

<!-- Modal -->
<div class="modal fade" id="itemModal" tabindex="-1" aria-labelledby="modalTitle" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header border-0">
                <h5 class="modal-title" id="modalTitle">Modal title</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="d-flex modal-details flex-column">
                <div class="modal-body" id="modalBody"></div>
            </div>
        </div>
    </div>
</div>

<script>
    // Select the modal element
    const modal = document.getElementById('itemModal');

    // Event listener for when the modal is about to be shown
    modal.addEventListener('show.bs.modal', function (event) {
        // Button that triggered the modal
        const button = event.relatedTarget;

        // Extract info from data attributes
        const title = button.getAttribute('data-title');
        const description = button.getAttribute('data-description');

        // Update the modal content
        document.getElementById('modalTitle').textContent = title;
        document.getElementById('modalBody').textContent = description;
    });
</script>

templates/landing_page/includes/nav.html
{% load static %}
{% load translations_tags %}

<!-- Sticky Navbar -->
<nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'landing_page:index' lang=request.language %}">
            <img src="{% static 'assets/images/logo.webp' %}" alt="Dikaioma Elpidas Logo">
        </a>

        <dropdown class="d-block d-lg-none mob-langs">
            <input id="toggle3" type="checkbox">
            <label for="toggle3" class="animate text-uppercase"><i class="fa-solid fa-globe"></i></label>
            <ul class="animate">
                {% for lang_code, lang_name in request.available_languages %}
                <li class="animate lang-item text-uppercase" data-value="{{ lang_code }}" {% if lang_code == request.language %}selected{% endif %}> {{ lang_code }}</li>
                {% endfor %}
            </ul>
        </dropdown>
        <button class="navbar-toggler custom-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="bar bar1"></span>
            <span class="bar bar2"></span>
            <span class="bar bar3"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ms-auto">
                <li class="nav-item">
                    <a class="nav-link{% if  request.resolver_match.url_name == 'index' %} active{% endif %}"
                       href="{% url 'landing_page:index' lang=request.language %}">{% trans 'menu_home' %}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link{% if  request.resolver_match.url_name == 'support' %} active{% endif %} me-0"
                       href="{% url 'landing_page:support' lang=request.language %}">{% trans 'menu_support_us' %}</a>
                </li>
                <li  class="nav-item">
                    <a class="nav-link{% if  request.resolver_match.url_name == 'contact' %} active{% endif %}"
                       href="{% url 'landing_page:contact' lang=request.language %}">{% trans 'menu_contact_us' %}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link{% if  request.resolver_match.url_name == 'events' %} active{% endif %}"
                       href="{% url 'landing_page:events' lang=request.language page=1 %}">{% trans 'menu_events' %}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link{% if  request.resolver_match.url_name == 'services' %} active{% endif %}"
                       href="{% url 'landing_page:services' lang=request.language %}">{% trans 'menu_actions' %}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link{% if  request.resolver_match.url_name == 'news' %} active{% endif %}"
                       href="{% url 'landing_page:news' lang=request.language page=1 %}">{% trans 'menu_news' %}</a>
                </li>
            </ul>

            <dropdown>
                <input id="toggle2" type="checkbox">
                <label for="toggle2" class="animate text-uppercase"><i class="fa-solid fa-globe"></i></label>
                <ul class="animate">
                    {% for lang_code, lang_name in request.available_languages %}
                        <li class="animate lang-item text-uppercase" data-value="{{ lang_code }}" {% if lang_code == request.language %}selected{% endif %}> {{ lang_code }}</li>
                    {% endfor %}
                </ul>
            </dropdown>

        </div>
    </div>
</nav>
<script>

    document.querySelectorAll(".lang-item").forEach(item => {
        item.addEventListener("click", function() {
            let selectedLang = this.dataset.value;
            let currentPath = window.location.pathname.split('/').slice(2).join('/'); // Remove first part (language)
            window.location.href = `/${selectedLang}/${currentPath}`;
        });
    });

    document.querySelector('.navbar-toggler').addEventListener('click', function() {
        this.classList.toggle('active');
    });


</script>

templates/landing_page/includes/pagination.html
{% if posts_data.paginator.num_pages > 1 %}
<nav>
    <ul class="pagination justify-content-end mt-4">


        <!-- Previous Page -->
        <li class="page-item {% if not posts_data.has_previous %}disabled{% endif %} main-pagination-btn">
            <a class="page-link" href="{% if posts_data.has_previous %}{% url 'landing_page:'|add:request.resolver_match.url_name lang=request.language page=posts_data.previous_page_number %}{% else %}#{% endif %}">
               Previous
            </a>
        </li>

        <!-- Page Numbers -->
        {% for num in posts_data.paginator.page_range %}
        {% if num == posts_data.number %}
            <li class="page-item active"><a class="page-link" href="{% url 'landing_page:'|add:request.resolver_match.url_name lang=request.language page=num %}">{{ num }}</a></li>
        {% elif num > posts_data.number|add:'-3' and num < posts_data.number|add:'3' %}
            <li class="page-item"><a class="page-link" href="{% url 'landing_page:'|add:request.resolver_match.url_name lang=request.language page=num %}">{{ num }}</a></li>
        {% endif %}
        {% endfor %}

        <!-- Next Page -->
        <li class="page-item {% if not posts_data.has_next %}disabled{% endif %} main-pagination-btn">
            <a class="page-link" href="{% if posts_data.has_next %}{% url 'landing_page:'|add:request.resolver_match.url_name lang=request.language page=posts_data.next_page_number %}{% else %}#{% endif %}">
                Next
            </a>
        </li>

    </ul>
</nav>
{% endif %}

templates/landing_page/includes/popup.html
<!-- Announcement Popup -->
<div id="announcement-popup" class="popup hidden">
    <div class="popup-content">
        <span id="popup-close">&times;</span>
        <img id="popup-image" src="" alt="Announcement">
    </div>
</div>

<script>
    // Fetch the announcement
    fetch("{% url 'webtools:api-get-latest-active-announcement' %}")
        .then(response => {
            if (response.status === 204) return null;  // No announcement
            return response.json();
        })
        .then(announcement => {
            if (announcement && !isAnnouncementDismissed(announcement.id)) {
                showAnnouncementPopup(announcement);
            }
        });

    function showAnnouncementPopup(announcement) {
        document.getElementById("popup-image").src = announcement.image_name;
        document.getElementById("announcement-popup").style.display = "block";

        document.getElementById("popup-close").addEventListener("click", function () {
            document.getElementById("announcement-popup").style.display = "none";
            dismissAnnouncement(announcement.id);
        });
    }

    // Save dismissed announcement in cookies for 10 days
    function dismissAnnouncement(announcementId) {
        document.cookie = `dismissed_announcement=${announcementId}; max-age=${10 * 24 * 60 * 60}; path=/`;
    }

    // Check if the announcement was dismissed
    function isAnnouncementDismissed(announcementId) {
        let cookieValue = document.cookie.split("; ").find(row => row.startsWith("dismissed_announcement="));
        return cookieValue ? cookieValue.split("=")[1] === announcementId.toString() : false;
    }
</script>

templates/landing_page/includes/support.html
{% load static %}
{% load translations_tags %}


    <!-- First Row (Ensures Full Width) -->
    <div class="row g-3">  <!-- Added row wrapper and gap -->
        <div class="col-12 col-md-6 col-lg-4 support-box">
            <div class="box d-flex flex-column justify-content-top">
                <div class="box-icon">
                    <img src="{% static 'assets/images/jcc-logo.png' %}" class="img-fluid" alt="jcc">
                </div>
                <span class="d-block box-title fs-4 text-start mt-3">{% trans 'get_involved_supporter_title' %}</span>
                <div class="break-line"></div>
                <span class="d-block box-details fs-5 text-start mt-3">{% trans 'get_involved_supporter_subtitle' %}</span>
                <div class="d-flex justify-content-end mt-auto">
                    <a href="https://www.jccsmart.com/businesses/50126028" target="_blank" class="w-auto mt-5">
                        <i class="fa-solid fa-arrow-right fs-5"></i>
                    </a>
                </div>
            </div>
        </div>
        <div class="col-12 col-md-6 col-lg-4 support-box">
            <div class="box d-flex flex-column justify-content-top">
                <div class="box-icon">
                    <img src="{% static 'assets/images/gift.png' %}" class="img-fluid" alt="Alternative Gift Giving">
                </div>
                <span class="d-block box-title fs-4 text-start mt-3">{% trans 'get_involved_contribution' %}</span>
                <div class="break-line"></div>
                <span class="d-block box-details fs-5 text-start mt-3">{% trans 'get_involved_contribution_subtitle' %}</span>
                <div class="d-flex justify-content-end mt-auto">
                    <a href="#" class="w-auto mt-5" data-bs-toggle="modal" data-bs-target="#involvedModal" data-title="{% trans 'get_involved_contribution' %}" data-first-paragraph="{% trans 'get_involved_contribution_par_1' %}" data-sec-paragraph="{% trans 'get_involved_contribution_par_2' %}" data-third-paragraph="{% trans 'get_involved_contribution_par_3' %}">
                        <i class="fa-solid fa-arrow-right fs-5"></i>
                    </a>
                </div>
            </div>
        </div>
        <div class="col-12 col-md-12 col-lg-4 support-box">
            <div class="box d-flex flex-column justify-content-top">
                <div class="box-icon">
                    <img src="{% static 'assets/images/donate.png' %}" class="img-fluid" alt="Memorial Donations">
                </div>
                <span class="d-block box-title fs-4 text-start mt-3">{% trans 'get_involved_memorial' %}</span>
                <div class="break-line"></div>
                <span class="d-block box-details fs-5 text-start mt-3">{% trans 'get_involved_memorial_subtitle' %}</span>
                <div class="d-flex justify-content-end mt-auto">
                    <a href="#" class="w-auto mt-5" data-bs-toggle="modal" data-bs-target="#involvedModal" data-title="{% trans 'get_involved_memorial' %}" data-first-paragraph="{% trans 'get_involved_memorial_par_1' %}" data-sec-paragraph="{% trans 'get_involved_memorial_par_2' %}" data-third-paragraph="{% trans 'get_involved_memorial_par_3' %}">
                        <i class="fa-solid fa-arrow-right fs-5"></i>
                    </a>
                </div>
            </div>
        </div>
    </div>

    <!-- Second Row -->
    <div class="row g-3 mt-3"> <!-- Added spacing between rows -->
        <div class="col-12 col-md-6 support-box">
            <div class="box d-flex flex-column justify-content-top">
                <div class="box-icon">
                    <img src="{% static 'assets/images/volunteer.png' %}" class="img-fluid" alt="Volunteer with Us">
                </div>
                <span class="d-block box-title fs-4 text-start mt-3">{% trans 'get_involved_volunteer' %}</span>
                <div class="break-line"></div>
                <span class="d-block box-details fs-5 text-start mt-3">{% trans 'get_involved_volunteer_subtitle' %}</span>
                <div class="d-flex justify-content-end mt-auto">
                    <a href="#" class="w-auto mt-5" data-bs-toggle="modal" data-bs-target="#involvedModal" data-title="{% trans 'get_involved_volunteer' %}" data-first-paragraph="{% trans 'get_involved_volunteer_par_1' %}" data-sec-paragraph="{% trans 'get_involved_volunteer_par_2' %}" data-third-paragraph="{% trans 'get_involved_volunteer_par_3' %}">
                        <i class="fa-solid fa-arrow-right fs-5"></i>
                    </a>
                </div>
            </div>
        </div>
        <div class="col-12 col-md-6 support-box">
            <div class="box d-flex flex-column justify-content-top">
                <div class="box-icon">
                    <img src="{% static 'assets/images/corporate.png' %}" class="img-fluid" alt="Corporate Giving">
                </div>
                <span class="d-block box-title fs-4 text-start mt-3">{% trans 'get_involved_company_support' %}</span>
                <div class="break-line"></div>
                <span class="d-block box-details fs-5 text-start mt-3">{% trans 'get_involved_company_support_subtitle' %}</span>
                <div class="d-flex justify-content-end mt-auto">
                    <a href="#" class="w-auto mt-5" data-bs-toggle="modal" data-bs-target="#involvedModal" data-title="{% trans 'get_involved_company_support' %}" data-first-paragraph="{% trans 'get_involved_company_support_par_1' %}" data-sec-paragraph="{% trans 'get_involved_company_support_par_2' %}" data-third-paragraph="{% trans 'get_involved_company_support_par_3' %}">
                        <i class="fa-solid fa-arrow-right fs-5"></i>
                    </a>
                </div>
            </div>
        </div>
    </div>