client_messages/urls.py
# django
from django.urls import path
# local
from . import views

app_name = "client_messages"

urlpatterns = [
    path("api/submit-contact-us-messages", views.submit_contact_us_message, name="api-submit-contact-us-messages"),
    path("api/submit-volunteer-application", views.submit_volunteer_application, name="api-submit-volunteer-application"),
]

dikeomaelpidas/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("landing_page.urls")),
    path("client_messages/", include("client_messages.urls")),
    path("webtools/", include("webtools.urls")),

    path("ckeditor5/", include("django_ckeditor_5.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

landing_page/urls.py
# Django
from django.urls import path
# Local
from . import views

app_name = "landing_page"

urlpatterns = [
    path("<str:lang>/", views.index, name="index"),
    path("<str:lang>/about/", views.about, name="about"),
    path("<str:lang>/services/", views.services, name="services"),
    path("<str:lang>/events/<int:page>/", views.posts_list, name="events"),
    path("<str:lang>/event/<int:post_id>/", views.posts_detail, name="event_detail"),
    path("<str:lang>/news/<int:page>/", views.posts_list, name="news"),
    path("<str:lang>/new/<int:post_id>/", views.posts_detail, name="new_detail"),
    path("<str:lang>/contact/", views.contact, name="contact"),
    path("<str:lang>/support/", views.support, name="support"),
    path("<str:lang>/team/", views.team, name="team"),
]

webtools/urls.py
# django
from django.urls import path
# local
from . import views

app_name = "webtools"

urlpatterns = [
    path("api/get-latest-active-announcement", views.get_latest_active_announcement,
         name="api-get-latest-active-announcement"),
]

landing_page/views.py
# django
from django.contrib.admin.models import LogEntry
from django.core.paginator import Paginator
from django.shortcuts import render, redirect
from django.urls import reverse
# local
from landing_page.functions import get_team_members_data, get_posts_data, get_single_post_data, \
    get_available_programs_data
from news_and_events.models import Post
from programs.models import Program
from team_members.models import Member
from translations.decorators import get_translations_information
from webtools.decorators import get_contact_information


@get_contact_information
@get_translations_information
def index(request, lang="en"):
    """
    This view is used to render the index.html
    :param lang:
    :param request:
    :return:
    """
    template = "landing_page/index.html"
    available_programs = get_available_programs_data()
    context = {"contact_information": request.contact_information,
               "available_programs": available_programs}
    return render(request, template, context)


@get_contact_information
@get_translations_information
def about(request, lang="en"):
    """
    This view is used to render the about page
    :param lang:
    :param request:
    :return:
    """
    template = "landing_page/about.html"
    context = {"contact_information": request.contact_information}
    return render(request, template, context)


@get_contact_information
@get_translations_information
def services(request, lang="en"):
    """
    This view is used to render the services page
    :param lang:
    :param request:
    :return:
    """
    template = "landing_page/services.html"
    available_programs = get_available_programs_data()
    context = {"contact_information": request.contact_information,
               "available_programs": available_programs}
    return render(request, template, context)


@get_contact_information
@get_translations_information
def posts_list(request, lang="en", page=1):
    """
    This view is used to render the events page
    :param page:
    :param lang:
    :param request:
    :return:
    """
    template = "landing_page/posts_list.html"
    # Get full URL from request, to determine content logic
    full_url = request.get_full_path()
    if "events" in full_url:
        posts_category = "events_category"
    elif "news" in full_url:
        posts_category = "news_category"
    else:
        # In case of wrong url usage, send user to homepage
        return redirect(reverse("landing_page:index", kwargs={"lang": lang}))

    # Get all posts data
    posts_data = get_posts_data(lang, posts_category)
    # Paginate based on requested page
    posts_paginator = Paginator(posts_data, 12)
    posts_current_page = posts_paginator.get_page(page)
    context = {"contact_information": request.contact_information,
               "posts_data": posts_current_page}
    return render(request, template, context)


@get_contact_information
@get_translations_information
def posts_detail(request, lang="en", post_id=None):
    """
    View used to handle single post view
    :param request:
    :param lang:
    :param post_id:
    :return:
    """
    template = "landing_page/post_detail.html"
    # Get full URL from request, to determine content logic
    full_url = request.get_full_path()
    if "event" in full_url:
        # Redirect to homepage if post detail is accessed without id
        if not post_id:
            return redirect(reverse("landing_page:events", kwargs={"lang": lang, "page": 1}))
        posts_category = "events_category"
    elif "new" in full_url:
        # Redirect to homepage if post detail is accessed without id
        if not post_id:
            return redirect(reverse("landing_page:news", kwargs={"lang": lang, "page": 1}))
        posts_category = "news_category"
    else:
        return redirect(reverse("landing_page:index", kwargs={"lang": lang}))
    post_data = get_single_post_data(lang, post_id)
    # If no post data found redirect to the correct post page
    if not post_data:
        if "event" in full_url:
            return redirect(reverse("landing_page:events", kwargs={"lang": lang, "page": 1}))
        elif "new" in full_url:
            return redirect(reverse("landing_page:news", kwargs={"lang": lang, "page": 1}))

    # Get more articles data
    posts_data = get_posts_data(lang, posts_category)
    # Paginate based on requested page
    posts_paginator = Paginator(posts_data, 12)
    extra_posts = posts_paginator.get_page(1)
    context = {"contact_information": request.contact_information,
               "post_data": post_data,
               "extra_posts": extra_posts}
    return render(request, template, context)


@get_contact_information
@get_translations_information
def contact(request, lang="en"):
    """
    This view is used to render the contact page
    :param lang:
    :param request:
    :return:
    """
    template = "landing_page/contact.html"
    context = {"contact_information": request.contact_information}
    return render(request, template, context)


@get_contact_information
@get_translations_information
def support(request, lang="en"):
    """
    This view is used to render the support page
    :param lang:
    :param request:
    :return:
    """
    template = "landing_page/support.html"
    context = {"contact_information": request.contact_information}
    return render(request, template, context)


@get_contact_information
@get_translations_information
def team(request, lang="en"):
    """
    This view is used to render the support page
    :param lang:
    :param request:
    :return:
    """
    template = "landing_page/team.html"
    team_members_data = get_team_members_data()
    context = {"contact_information": request.contact_information,
               "team_members_data": team_members_data}
    return render(request, template, context)


def dashboard_callback(request, context):
    # Gather Total Posts
    posts_count = Post.objects.count()
    context["posts_count"] = posts_count
    # Gather Total Team Members
    team_members_count = Member.objects.count()
    context["team_members_count"] = team_members_count
    # Gather Total Programs
    programs_count = Program.objects.count()
    context["programs_count"] = programs_count
    # Gather Recent Actions
    recent_actions = LogEntry.objects.all().order_by('-action_time')[:5]
    context["recent_actions"] = recent_actions
    return context

templates/landing_page/about.html
{% extends "landing_page/base.html" %}
{% load static %}

{% block SEO %}
    <title>About us | Dikaioma Elpidas</title>
    <meta name="description"
          content="Dikaioma Elpidas is a school dedicated to inclusive education and therapeutic support for
           individuals with special needs. Our vision is to empower every student with the skills,
            care, and opportunities they deserve in a nurturing and supportive environment.">
{% endblock %}

{% block EXTRA_HEAD %}
    {# to be extended in templates #}
{% endblock %}

{% block BODY %}
<div class="nav-margin">
    <div class="container-lg container-xlarge">
        <div>
            <span class="d-block main-title">Our Journey of Hope & Inclusion</span>
            <span class="d-block sub-title mt-3">Learn about our history, mission, and commitment to empowering individuals with special needs through education and therapy.</span>
        </div>

        <div class="row g-4 justify-content-center about-image-container mt-165 mb-165">
            <div class="col-6 col-lg-3">
                <div class="image-box image-box-1">
                    <img src="{% static 'assets/images/mission.webp' %}" class="img-fluid rounded" alt="Image 1">
                </div>
            </div>
            <div class="col-6 col-lg-3">
                <div class="image-box image-box-2">
                    <img src="{% static 'assets/images/mission.webp' %}" class="img-fluid rounded" alt="Image 2">
                </div>
            </div>
            <div class="col-6 col-lg-3">
                <div class="image-box image-box-3">
                    <img src="{% static 'assets/images/mission.webp' %}" class="img-fluid rounded" alt="Image 3">
                </div>
            </div>
            <div class="col-6 col-lg-3">
                <div class="image-box image-box-4">
                    <img src="{% static 'assets/images/mission.webp' %}" class="img-fluid rounded" alt="Image 4">
                </div>
            </div>
        </div>

        <div class="row justify-content-center mt-335 mb-165">
            <div class="main-break-line blue-color"></div>
            <span class="main-title mt-4 text-center fs-45">Our Story</span>
            <span class="d-block box-details fs-5 text-center mt-3 p-0">Founded in [Year], Δικαίωμα Ελπίδας was created with a vision to provide inclusive education and <br> therapeutic support for individuals with special needs.</span>
        </div>

        <div class="row pt-lg-5">
            <div class="col-12 col-lg-8 mt-5">
                <span class="story-title">[Year of Founding] – The Beginning</span>
                <ul class="mt-3">
                    <li class="story-li mb-2">Δικαίωμα Ελπίδας was founded with a vision to provide inclusive education and therapeutic support for individuals with special needs.</li>
                    <li class="story-li">Started with [X] students and [X] staff members.</li>
                </ul>
            </div>
            <div class="col-12 col-lg-4">
                <img class="story-img-1 img-fluid" src="{% static 'assets/images/mission.webp' %}" alt="Image 1">
            </div>
        </div>

        <div class="row mt-5 pt-5">
            <div class="col-12 col-lg-6 order-1 order-lg-0">
                <img class="story-img-2 img-fluid" src="{% static 'assets/images/mission.webp' %}" alt="Image 1">
            </div>
            <div class="col-12 col-lg-6 mt-lg-5 order-0 order-lg-1">
                <span class="story-title">[Year] – Recognized for Excellence</span>
                <ul class="mt-3">
                    <li class="story-li mb-2">Received [Award or Certification] for innovation in special education.</li>
                    <li class="story-li">Featured in [Media/TV show], highlighting our impact.</li>
                </ul>
            </div>
        </div>

        <div class="row mt-5 pt-5">
            <div class="col-12 col-lg-8 mt-lg-5">
                <span class="story-title">[Year] – European Collaborations Begin</span>
                <ul class="mt-3">
                    <li class="story-li mb-2">Partnered with [Program Name], joining a network of European educational initiatives.</li>
                    <li class="story-li">Hosted our first international student exchange program.</li>
                </ul>
            </div>
            <div class="col-12 col-lg-4">
                <img class="story-img-1 img-fluid" src="{% static 'assets/images/mission.webp' %}" alt="Image 1">
            </div>
        </div>

        <div class="row mt-5 pt-5">
            <div class="col-12 mt-lg-5">
                <span class="d-block story-title text-center">[Year] – European Collaborations Begin</span>
                <ul class="mt-3">
                    <li class="max-content mx-auto story-li mb-2 text-center">Partnered with [Program Name], joining a network of European educational initiatives.</li>
                    <li class="max-content mx-auto story-li text-center">Hosted our first international student exchange program.</li>
                </ul>
            </div>
            <div class="col-12 d-flex justify-content-center mt-lg-5">
                <img class="story-img-3 img-fluid" src="{% static 'assets/images/mission.webp' %}" alt="Image 1">
            </div>
        </div>

        <div class="row justify-content-center mt-335">
            <div class="main-break-line pink-color"></div>
            <span class="main-title mt-4 text-center fs-45">Our Mission & Values</span>
            <span class="d-block box-details fs-5 text-center mt-3 p-0">Empowering lives through education, therapy, and inclusion.</span>
            <div class="my-5">
                <div class="row g-4">
                    <div class="col-md-6">
                        <div class="custom-card p-4">
                            <i class="custom-card-icon fa-solid fa-globe blue-text mb-4"></i>
                            <h5>Inclusion</h5>
                            <p>Learning transforms lives.</p>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="custom-card p-4">
                            <i class="custom-card-icon fa-solid fa-heart pink-text mb-4"></i>
                            <h5>Compassion</h5>
                            <p>We care for every individual.</p>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="custom-card p-4 ">
                            <i class="custom-card-icon fa-solid fa-graduation-cap green-text mb-4"></i>
                            <h5>Education</h5>
                            <p>Everyone deserves a place to grow.</p>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="custom-card p-4">
                            <i class="custom-card-icon fa-solid fa-graduation-cap green-text mb-4"></i>
                            <h5>Community</h5>
                            <p>Together, we make a difference.</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="d-flex mt-3 justify-content-center">
                <a class="justify-content-center main-button pink-btn me-3"  href="{% url 'landing_page:team' lang=request.language %}">
                    <span>Meet the team</span>
                </a>
                <a class="justify-content-center main-button green-color"  href="{% url 'landing_page:services' lang=request.language %}">
                    <span>Explore Programs</span>
                </a>
            </div>
        </div>

    </div>
</div>

{% endblock %}

templates/landing_page/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    {% block SEO %}

    {% endblock %}
    <!-- Bootstrap 5 -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">

    <link rel="icon" type="image/webp" href="{% static 'assets/images/favicon.ico' %}">

    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
          crossorigin="anonymous" referrerpolicy="no-referrer"/>
    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'assets/css/main.css' %}?v=2">

    <!-- AOS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/aos/2.3.4/aos.css" />

    <!-- Add this inside <head> or before closing </body> -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.min.css">
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick-theme.min.css">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.min.js"></script>


    {% block EXTRA_HEAD %}
        {# to be extended in templates #}
    {% endblock %}
</head>
<body class="{{ request.resolver_match.url_name }} body-{{request.language}} p-0" id="{{ request.resolver_match.url_name }}">

{% include "landing_page/includes/nav.html" %}
{% block BODY %}

{% endblock %}

{% include "landing_page/includes/popup.html" %}

{% include "landing_page/includes/footer.html" %}

<!-- JavaScript to Include Components -->
<script src="{% static 'scripts/includes.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>



</body>
</html>

templates/landing_page/index.html
{% extends "landing_page/base.html" %}
{% load static %}
{% load translations_tags %}

{% block SEO %}
    <title>{% trans 'menu_home' %} | {% trans 'tab_title' %}</title>
    <meta name="description" content="{% trans 'seo_text' %}">
{% endblock %}

{% block EXTRA_HEAD %}
    {# to be extended in templates #}
{% endblock %}

{% block BODY %}
    <!-- Main Content -->
    <div class="homepage">
        <div class="video-container">
            <video autoplay muted loop playsinline>
                <source src="{% static 'assets/videos/home_vid.mp4' %}" type="video/mp4">
                <source src="{% static 'assets/videos/home_vid.webm' %}" type="video/webm">
            </video>
        </div>

        <div class="container-lg">

            <!-- Hero Boxes -->
            <section style="margin-top:0px">
                <div class="boxes-container justify-content-center p-0">
                    <div class="row w-100 gy-4 gx-md-3">
                        <div class="col-12 col-md-4 about-us p-0 px-md-2">
                            <div class="box d-block">
                                <div class="box-icon">
                                    <i class="fa-solid fa-heart"></i>
                                </div>
                                <span class="d-block box-title fs-4 text-start mt-3">{% trans 'hero_about_us' %}</span>
                                <div class="break-line"></div>
                                <span class="d-block box-details fs-5 text-start mt-3">{% trans 'hero_about_us_subtitle' %}</span>
                                <a class="card-btn justify-content-end mt-5" href="{% url 'landing_page:services' lang=request.language %}">
                                    <span class="me-2">{% trans 'general_read_more' %}</span>
                                    <i class="fa-solid fa-arrow-right"></i>
                                </a>
                            </div>
                        </div>

                        <div class="col-12 col-md-4 meet-team p-0 px-md-2">
                            <div class="box d-block">
                                <div class="box-icon">
                                    <i class="fa-regular fa-face-smile"></i>
                                </div>
                                <span class="d-block box-title fs-4 text-start mt-3">{% trans 'hero_meet_the_team' %}</span>
                                <div class="break-line"></div>
                                <span class="d-block box-details fs-5 text-start mt-3">{% trans 'hero_meet_the_team_subtitle' %}</span>
                                <a class="card-btn justify-content-end mt-5" href="{% url 'landing_page:team' lang=request.language %}">
                                    <span class="me-2">{% trans 'general_read_more' %}</span>
                                    <i class="fa-solid fa-arrow-right"></i>
                                </a>
                            </div>
                        </div>

                        <div class="col-12 col-md-4 actions-europe p-0 px-md-2">
                            <div class="box d-block">
                                <div class="box-icon">
                                    <i class="fa-solid fa-graduation-cap"></i>
                                </div>
                                <span class="d-block box-title fs-4 text-start mt-3">{% trans 'menu_actions' %}</span>
                                <div class="break-line"></div>
                                <span class="d-block box-details fs-5 text-start mt-3">{% trans 'hero_actions_programs' %}</span>
                                <a class="card-btn justify-content-end mt-5" href="{% url 'landing_page:services' lang=request.language %}">
                                    <span class="me-2">{% trans 'general_read_more' %}</span>
                                    <i class="fa-solid fa-arrow-right"></i>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </section>


            <!-- Discover our Mission -->
            <section style="margin-top:80px;">
                <div id="mission-section" class="row mt-5 justify-content-center "  >
                    <div class="col-12 col-md-5 order-1 order-md-0 position-relative" data-aos="fade-right" >
                        <img height="400" src="{% static 'assets/images/mission.webp' %}" class="img-fluid radius-40 mission-img" alt="Mission of Dikaioma Elpidas">
                        <img height="200" src="{% static 'assets/images/brush-blue-2.png' %}" class="img-fluid brush-img" alt="Blue brush">
                    </div>
                    <div class="col-12 col-md-5 d-flex align-items-center order-0 order-md-1" data-aos="fade-left">
                        <div class="row">
                            <div class="col-12 mb-4 mb-lg-0">
                                <div class="main-break-line"></div>
                                <span class="d-block main-title mt-4">{% trans 'discover_our_mission' %}</span>
                                <span class="d-block box-details fs-5  text-start mt-3 p-0">{% trans 'discover_our_mission_text' %}</span>
                                <a class="justify-content-center main-button blue-btn d-none d-md-block" href="{% url 'landing_page:about' lang=request.language %}">
                                    <span class="me-2">{% trans 'general_read_more' %}</span>
                                    <i class="fa-solid fa-arrow-right"></i>
                                </a>
                            </div>
                        </div>
                    </div>
                    <a class="justify-content-center main-button blue-btn d-block d-md-none order-2" href="#">
                        <span class="me-2">{% trans 'general_read_more' %}</span>
                        <i class="fa-solid fa-arrow-right"></i>
                    </a>
                </div>
            </section>

            <!-- Meet our team -->
            <section>
                <div id="meet-team" class="row justify-content-center text-center" data-aos="fade-up">
                    <div class="col-12">
                        <div class="main-break-line mx-auto"></div>
                        <span class="d-block main-title mt-4">{% trans 'meet_our_team_title' %}</span>
                        <span class="d-block box-details fs-5 mt-3">{% trans 'meet_our_team_text_1' %}</span>
                        <img src="{% static 'assets/images/meet-team.webp' %}" class="img-fluid radius-40 mt-5 w-100" alt="Team of Dikaioma Elpidas">
                        <span class="d-block box-details fs-5 mt-4">{% trans 'meet_our_team_text_2' %}</span>
                        <a class="d-inline-flex align-items-center main-button pink-btn" href="{% url 'landing_page:team' lang=request.language %}">
                            <span class="me-2">{% trans 'general_read_more' %}</span>
                            <i class="fa-solid fa-arrow-right"></i>
                        </a>
                    </div>
                </div>
            </section>


            <!-- What we offer -->
            <section>
                <div id="programs-section" class="row" data-aos="fade-up">
                    <div class="col-12">
                        <span class="d-block hero-subtitle box-details green-text p-0 text-start">{% trans 'what_we_offer_subtitle_1' %}</span>
                        <span class="d-block main-title mt-2 text-start">{% trans 'what_we_offer_title' %}</span>
                        <span class="d-block box-details fs-5 mt-2 mb-5 p-0 text-start">{% trans 'what_we_offer_subtitle_2' %}</span>
                    </div>

                    <div class="col-12">
                        {% for program in available_programs.standard_programs %}
                            <span class="program-tag">{% trans program.name %}</span>
                        {% endfor %}
                    </div>

                    <div class="d-flex justify-content-end">
                        <a class="justify-content-center main-button text-dark" href="{% url 'landing_page:services' lang=request.language %}">
                            <span class="me-2">{% trans 'general_explore_programs' %}</span>
                            <i class="fa-solid fa-arrow-right"></i>
                        </a>
                    </div>
                </div>

            </section>

            <!-- Support Us -->
            <section>
                <div id="support-section" class="row" data-aos="fade-up">
                    <div class="col-12">
                        <div class="main-break-line mx-auto mx-lg-0"></div>
                        <span class="d-block main-title mt-4 text-center text-lg-start">{% trans 'get_involved_title' %}</span>
                        <span class="d-block box-details fs-5 mt-3 p-0 text-center text-lg-start">{% trans 'get_involved_subtitle' %}</span>
                    </div>
                    <div class="mt-5">
                        <!-- Include Support section -->
                        {% include "landing_page/includes/support.html" %}
                    </div>
                </div>
            </section>

        </div>

    </div>

{% include "landing_page/includes/involved-modal.html" %}


<script src="https://cdnjs.cloudflare.com/ajax/libs/aos/2.3.4/aos.js"></script>
    <script>
        AOS.init();
    </script>

{% endblock %}

templates/landing_page/post_detail.html
{% extends "landing_page/base.html" %}
{% load static %}
{% load translations_tags %}

{% block SEO %}
<title>{% trans post_data.title %} | {% trans 'tab_title' %}</title>
<meta property="og:title" name="description" content='{% trans post_data.title %}'>
<meta property="og:image" content="{{ post_data.image_url }}">
<meta property="og:description" name="description" content='{{ post_data.content|slice:":300" }}'>
{% endblock %}

{% block EXTRA_HEAD %}
{# to be extended in templates #}
{% endblock %}

{% block BODY %}
<div class="nav-margin mb-5 pb-5">
    <div class="container-lg">
        <div>
            <span class="d-block article-title text-start">
               {% trans post_data.title %}
            </span>
            <span class="d-block article-datetime mt-4 text-start">August 20, 2022</span>
        </div>
        <img src="{{ post_data.image_url }}" class="article-details-img my-5"
             alt="{{ post_data.title }}" loading="lazy">
        <div class="article-details">
            {{ post_data.content|safe }}
        </div>
    </div>
</div>

<div class="continue-reading-container">
    <span class="d-block article-title text-start mx-3">Continue reading</span>
    <div class="your-slider">
        {% for post in extra_posts %}
        {% if post.id != post_data.parent_post_id|default:0 %}
        <div class="mt-4 ms-lg-3"> <!-- Each box takes 1/4th of the row -->
            <a href="{{ post.post_detail_url }}" class="text-decoration-none d-block w-100">
                <div class="card p-3">
                    <img src="{{ post.image_url }}" class="card-img-top article-img"
                         alt="{{ post.title }}" loading="lazy">
                    <div class="card-body">
                        <h5 class="card-title">{% trans post.title %}</h5>
                        <p class="text-muted mb-0 mt-4">{{ post.published_date }}</p>
                    </div>
                </div>
            </a>
        </div>
        {% endif %}
        {% endfor %}
    </div>
</div>
<script>
    $(document).ready(function(){
        $('.your-slider').slick({
            slidesToShow: 3,
            slidesToScroll: 1,
            autoplay: false,
            autoplaySpeed: 2000,
            arrows: true,
            infinite: false,
            responsive: [
                {
                    breakpoint: 768, // For screens smaller than 768px
                    settings: {
                        arrows: false,  // Hide arrows on mobile
                        dots: true, // Show dots instead
                        slidesToShow: 1, // Show 1 slide at a time
                        centerMode: true,  // Enables spacing effect
                        centerPadding: '20px' // Adjusts space
                    }
                }
            ]
        });
    });
</script>
{% endblock %}